#!/usr/bin/env python3
"""Generate ThreeStep/Data.lean from the exact appendix CSV; --check is read-only."""
from __future__ import annotations
import argparse
import csv
import hashlib
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HISTORIES = (("N", "Bo", "Ro"), ("N", "Bo", "R"), ("N", "B", "Ro"),
             ("N", "B", "R"), ("B", "B", "Ro"), ("B", "B", "R"))
FIELDS = ("state_id", "a", "b", "r", "U", "L", "c0", "c1", "c2", "c3", "c4")

def render() -> str:
    source = ROOT / "data/three_step_weights.csv"
    with source.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if tuple(reader.fieldnames or ()) != FIELDS:
            raise ValueError("Unexpected CSV columns")
        rows = list(reader)
    states = [(h, U, L) for h in HISTORIES
              for U in product(("Bo", "B"), repeat=3)
              for L in product(("Ro", "R"), repeat=3)]
    if len(rows) != len(states):
        raise ValueError("Expected exactly 384 states")
    polynomials, indices = [], []
    for i, (row, (h, U, L)) in enumerate(zip(rows, states), 1):
        if (row["state_id"] != f"q{i:03d}" or
            tuple(row[k] for k in ("a", "b", "r")) != h or
            tuple(row["U"].split()) != U or tuple(row["L"].split()) != L):
            raise ValueError(f"Unexpected state or ordering at row {i}")
        # This certificate has integer coefficients. No floats or approximations.
        p = tuple(int(row[f"c{j}"]) for j in range(5))
        if p not in polynomials:
            polynomials.append(p)
        indices.append(polynomials.index(p))
    if len(polynomials) != 139:
        raise ValueError("Expected the appendix's 139 distinct polynomials")
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    lines = ["import ThreeStep.Arithmetic", "",
             "/-! Generated by tools/generate_data.py; do not edit the tables by hand.",
             "The CSV is identical to the canonical appendix data.",
             f"SHA-256: {digest}",
             "The Lean index j denotes the printed polynomial w_(j+1). -/", "",
             "namespace ThreeStep", "",
             "def weightPolynomials : Fin 139 → Coeffs := !["]
    for j, p in enumerate(polynomials):
        comma = "," if j < len(polynomials)-1 else ""
        lines.append("  ![" + ", ".join(map(str,p)) + "]" + comma + f" -- w{j+1}")
    lines += ["]", "", "/-- History, blue window, red window: the appendix's six 8×8 grids. -/",
              "def weightIndex : Fin 6 → Fin 8 → Fin 8 → Fin 139 := !["]
    for h in range(6):
        lines.append("  ![ -- " + ",".join(HISTORIES[h]))
        for u in range(8):
            vals = indices[h*64+u*8:h*64+(u+1)*8]
            lines.append("    ![" + ", ".join(map(str,vals)) + "]" + ("," if u<7 else ""))
        lines.append("  ]" + ("," if h<5 else ""))
    lines += ["]", "", "end ThreeStep", ""]
    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "ThreeStep/Data.lean"
    text = render()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            raise SystemExit("FAIL: Data.lean does not match the canonical CSV")
        print("PASS: Data.lean matches all 384 canonical state weights exactly.")
    else:
        target.write_text(text, encoding="utf-8")
        print(f"Generated {target}")

if __name__ == "__main__":
    main()
